edition = "2024"
style_edition = "2024"
unstable_features = true
comment_width = 80
wrap_comments = true
normalize_comments = true
enum_discrim_align_threshold = 20
# float_literal_trailing_zero = "IfNoPostfix"
imports_granularity = "Module"
group_imports = "StdExternalCrate"
imports_layout = "Mixed"
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = false
reorder_modules = false
single_line_let_else_max_width = 0
struct_lit_single_line = false
trailing_comma = "Never"
use_field_init_shorthand = true
